# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 055466dcd4e877eaa49f3051e856f2d2c6807edf451460d2796ea26effa0a58a68310a79ebfecc4c73f6795a6656a71c6909ddfc200ff41c853dce3bde332be7

test:
  secret_key_base: 5defb8e86d71cc741ebfc751d3f05c4ec7eadcbdc51f81dbd73d3a9c8b35d4f64cddcf4023fa2b07bc1bf06191f450428f1e18c4b5918424a41a7f1fce24b3fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
